### PR TITLE
Update readme.md with Editors section

### PR DESCRIPTION
**Pull request by marcelonada**
Add editors section

### CODE REVIEW

**Comment by marcelonada** [comment]
Add Editors section

**Comment by camilleroux** [comment]
maybe a bit light with only 2 links for a section. Maybe you can add other "editors" like p5 editor, openprocessing, twigl, shadertoy... ?

**Review by camilleroux — CHANGES_REQUESTED** [review]
`✖  13:1  ToC item "Community" does not match corresponding heading "Editors"  remark-lint:awesome-toc`

**Comment by marcelonada** [comment]
As this is a document under collective construction, I thought I could indicate a section and have other people complement it. But that's ok, I'll try again another day.

**Pull request closed without merging**
