### PR TITLE
Added frameworks, corrected blockchains and added tools

### PR DESCRIPTION
**Pull request by vicdoval**
Sorry I added many suggestions in one pull request but otherways it takes too long in this fast paced times :)

### CODE REVIEW

**Review by camilleroux — CHANGES_REQUESTED** [review]
```
  ✖  12:3   ToC missing item for "Tools"                            remark-lint:awesome-toc
  ✖  47:29  List item description must end with proper punctuation  remark-lint:awesome-list-item
  ✖  48:34  List item description must end with proper punctuation  remark-lint:awesome-list-item
  ✖  79:50  List item description must end with proper punctuation  remark-lint:awesome-list-item
  ✖  83:36  List item description must end with proper punctuation  remark-lint:awesome-list-item
```

**Comment by camilleroux** [comment]
✖  12:3   ToC missing item for "Tools"                            remark-lint:awesome-toc
  ✖  47:29  List item description must end with proper punctuation  remark-lint:awesome-list-item
  ✖  48:34  List item description must end with proper punctuation  remark-lint:awesome-list-item
  ✖  79:50  List item description must end with proper punctuation  remark-lint:awesome-list-item
  ✖  83:36  List item description must end with proper punctuation  remark-lint:awesome-list-item

**Comment by vicdoval** [comment]
What does this mean? :ToC missing item for "Tools"

**Comment by camilleroux** [comment]
ToC = Table of Contents
You just need to add the section in Contents

**Pull request merged**
